# Use a Python image with uv pre-installed
FROM ghcr.io/astral-sh/uv:python3.13-alpine

# This will be set by the GitHub action to the folder containing this component.
ARG FOLDER=/app

COPY --chown=1000:1000 . /app
WORKDIR ${FOLDER}

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Ensure installed tools can be executed out of the box
ENV UV_TOOL_BIN_DIR=/usr/local/bin

# Place executables in the environment at the front of the path
ENV PATH="$FOLDER/.venv/bin:$PATH"

# Install Node.js and nodemon for easy watch mode with Python
USER root
RUN apk update \
    && apk add nodejs npm \
    && npm install -g nodemon

# Allow uv to use cache
RUN mkdir -p /.cache/uv && chown 1000:1000 -R /.cache /.cache/uv

USER 1000:1000

# Reset the entrypoint, don't invoke `uv`
ENTRYPOINT []

EXPOSE 8000
ENV PORT=8000
ENV HOST="0.0.0.0"

CMD ["/usr/local/bin/nodemon", \
    "--delay", "1", \
    "--watch", "pyproject.toml", \
    "--watch", "requirements.txt", \
    "--watch", ".venv/lib/*", \ 
    "--watch", ".venv/lib64/*", \
    "--watch", "src", \ 
    "--ext", "py", \
    "--exec", "sh -c 'if [ -f pyproject.toml ]; then uv run --isolated --with . flask --app src/main.py run --host=0.0.0.0 --port=8000 --no-reload --debug; elif [ -f requirements.txt ]; then uv run --isolated --with-requirements requirements.txt flask --app src/main.py run --host=0.0.0.0 --port=8000 --no-reload --debug; else uv run --isolated flask --app src/main.py run --host=0.0.0.0 --port=8000 --no-reload --debug; fi'", \
    "--"]
